const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../agent_world/static/leaderboard.js'),'utf8');
const context=vm.createContext({data:{launches:[{run_id:'test',supervisor_thread_id:'monitor',monitor_reviewed:false,error:'internal error'}]},esc:String,number:String,relative:()=> '10m ago'});
vm.runInContext(source.slice(source.indexOf('const stateLabel'),source.indexOf('function renderActivity')),context);
context.run={id:'test',model:'Gemini',ranked:false,warnings:[],cells:[{seed:11,tick:11,target:60,state:'status_stale',operational_state:'needs_attention',attention:'decisions_unusable'}]};
let html=vm.runInContext('studyMarkup(run)',context);
assert.match(html,/Repair in progress/);
assert.match(html,/monitoring agent is working on a fix/);
assert.doesNotMatch(html,/Status out of date/);
assert.ok(html.indexOf('decisions_unusable')>html.indexOf('<details'));
context.data.launches[0].monitor_reviewed=true;
context.data.launches[0].monitor_resolution_reason='Provider login required';
html=vm.runInContext('studyMarkup(run)',context);
assert.doesNotMatch(html,/working on a fix/);
assert.match(html,/Provider login required/);
context.run.cells[0]={seed:11,tick:60,target:60,state:'completed',operational_state:'completed'};
html=vm.runInContext('studyMarkup(run)',context);
assert.doesNotMatch(html,/Repair in progress|internal error/);
console.log('Repair copy, diagnostic disclosure and resolved-state checks passed');
